apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  "tls.crt": |-
{{ .Files.Get "certs/server.crt" | b64enc | indent 4 }}
  "tls.key": |-
{{ .Files.Get "certs/server.key" | b64enc | indent 4 }}
