issuer: "none"
config:
  issuer: "none"
  storage:
      type: kubernetes
      config:
        inCluster: true
  logger:
    level: debug
  web:
    https: "0.0.0.0:443"
    tlsCert: /etc/dex/tls/https/server/tls.crt
    tlsKey: /etc/dex/tls/https/server/tls.key
  connectors:
  - type: ldap
    name: OpenLDAP
    id: ldap
    config:
      issuer: toreplacedbyissuer
      # No TLS for this setup.
      insecureNoSSL: true
      # This would normally be a read-only user.
      bindDN: "cn=admin,dc=example,dc=org"
      bindPW: admin
      groupSearch:
        baseDN: "ou=Groups,dc=example,dc=org"
        filter: (objectClass=groupOfNames)
        groupAttr: member
        nameAttr: cn
        userAttr: DN
      host: "10.138.0.26:389"
      insecureNoSSL: true
      userSearch:
        baseDN: "ou=People,dc=example,dc=org"
        emailAttr: mail
        filter: (objectClass=person)
        idAttr: DN
        nameAttr: cn
        username: mail
      usernamePrompt: "Email Address"
  oauth2:
      skipApprovalScreen: true
  staticClients:
  - id: example-app
    redirectURIs:
    - 'http://127.0.0.1:5555/callback'
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
service:
  name: dex
  type: LoadBalancer
  externalPort: 443
ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts: none
  serviceName: dex
  servicePort: 443
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/proxy-body-size: 8m
     nginx.ingress.kubernetes.io/secure-backends: "true"
     nginx.ingress.kubernetes.io/secure-verify-ca-secret: ca-secret-dex
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls:
     secretName: dex-key-cert
     hosts: none
resources: {}


