apiVersion: v1
kind: Secret
metadata:
  name: dex
data:
  config.yaml: {{ toYaml .Values.config | b64enc }}
  staticClient.id: {{ toYaml (index .Values.config.staticClients 0).id | b64enc }}
  staticClient.redirectURIs: {{ toYaml (index .Values.config.staticClients 0).redirectURIs | b64enc }}
  staticClient.secret: {{ toYaml (index .Values.config.staticClients 0).secret | b64enc }}
