image: "gcr.io/constant-cubist-173123/management-api"
tag: "latest"
service:
  name: management-api
  type: LoadBalancer
  externalPort: 443
ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
  - &man-api-host management-api.aipg.com
  serviceName: management-api
  servicePort: 443
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/secure-verify-ca-secret: ca-secret-ing-man-api
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls:
  # Secrets must be manually created in the namespace.
  - secretName: tls-management-secret
    hosts:
    - *man-api-host
resources: {}
