version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-jessie-browsers
    working_directory: ~/inferno-platform
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Create venv
          command: |
            cd ~/inferno-platform/
            python3 -m venv .venv
      - run:
          name: Style checker
          command: |
            . ~/inferno-platform/.venv/bin/activate
            pip install -q flake8
            echo "management folder" && cd ~/inferno-platform/management/ && make style
            echo "tests folder && " && cd ~/inferno-platform/tests/ && make style
      - run:
          name: Run unit tests
          command: |
            . ~/inferno-platform/.venv/bin/activate
            cd ~/inferno-platform/management/ && python setup.py test
      - run:
          name: Create k8s cluster
          command: |
            echo "${GOOGLE_INFERNO_KEY}" | base64 -d > /tmp/gcp-key.json
            export PR_NR=`basename ${CIRCLE_PULL_REQUEST}`
            export SHORT_SHA1=`echo ${CIRCLE_SHA1} | cut -c 1-6`
            export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
            export CLUSTER_NAME="inferno-${CIRCLE_BRANCH}-${SHORT_SHA1}"
            export CLUSTER_ALL_VMS_NETWORK="${CLUSTER_NAME}-all-vms-net"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk
            sudo apt-get install kubectl
            sudo apt-get update && sudo apt-get --only-upgrade install kubectl google-cloud-sdk google-cloud-sdk-app-engine-grpc google-cloud-sdk-pubsub-emulator \
            google-cloud-sdk-app-engine-go google-cloud-sdk-cloud-build-local google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-cbt \
            google-cloud-sdk-bigtable-emulator google-cloud-sdk-app-engine-python-extras google-cloud-sdk-datalab google-cloud-sdk-app-engine-java
            gcloud auth activate-service-account --key-file /tmp/gcp-key.json
            gcloud config set project "${GOOGLE_PROJECT_ID}"
            gcloud container clusters create $CLUSTER_NAME --zone us-west1-a --num-nodes 3 --machine-type "n1-standard-2" --min-cpu-platform "Intel Skylake"
            gcloud container clusters get-credentials $CLUSTER_NAME --zone us-west1-a --project "${GOOGLE_PROJECT_ID}"
            # The 3 commands below are necessary to create a connection between the cluster and our LDAP and keystone instances
            export NETWORK=`gcloud container clusters describe $CLUSTER_NAME --format=get"(network)" --zone=us-west1-a` 
            export CIDR=`gcloud container clusters describe $CLUSTER_NAME --format=get"(clusterIpv4Cidr)" --zone=us-west1-a`
            gcloud compute firewall-rules create $CLUSTER_ALL_VMS_NETWORK --network=$NETWORK --source-ranges=$CIDR --allow=tcp,udp,icmp,esp,ah,sctp
            kubectl create serviceaccount --namespace kube-system tiller
            kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
            curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
            chmod 700 get_helm.sh
            ./get_helm.sh
            helm init --service-account tiller --upgrade
            sleep 20
      - run:
          name: Check management api images version
          command: |
            cd ~/inferno-platform/
            export TAG=$(find management/ -type f -exec sha256sum {} \; | cut -d " " -f1 | sort | xargs echo | sha256sum | cut -d " " -f1)
            export TAG_EXISTS=$(gcloud container images list-tags gcr.io/constant-cubist-173123/management-api | grep $TAG)
            echo $TAG
            echo $TAG_EXISTS
            cd ~/inferno-platform/management
            if [ -z "$TAG_EXISTS" ]; then
               make circleci
            else
               echo "image already in registry - not rebuilding"
            fi
      - run:
          name: Check CRD controller image version
          command: |
            cd ~/inferno-platform
            export TAG=$(find server-controller/ -type f -exec sha256sum {} \; | cut -d " " -f1 | sort | xargs echo | sha256sum | cut -d " " -f1)
            export TAG_EXISTS=$(gcloud container images list-tags gcr.io/constant-cubist-173123/server-controller-prod | grep $TAG)
            echo $TAG
            echo $TAG_EXISTS
            cd ~/inferno-platform/server-controller/
            if [ -z "$TAG_EXISTS" ]; then
               printf "machine github.com\n        login jrozansk\n        password $NERVANA_FF\n" > .netrc
               make circleci
               git checkout -- .netrc
            else
               echo "image already in registry - not rebuilding"
            fi
      - run:
          name: Download dependencies and deploy platfrom
          command: |
            export MGMT_TAG=$(find management/ -type f -exec sha256sum {} \; | cut -d " " -f1 | sort | xargs echo | sha256sum | cut -d " " -f1)
            export CTRL_TAG=$(find server-controller/ -type f -exec sha256sum {} \; | cut -d " " -f1 | sort | xargs echo | sha256sum | cut -d " " -f1)
            cd ~/inferno-platform/helm-deployment/
            helm dep up .
            helm install --set management-api-chart.tag=$MGMT_TAG --set crd-subchart.tag=$CTRL_TAG -f dex-values.yaml .
            sleep 150
      - run:
          name: Run tests
          command: |
            . ~/inferno-platform/.venv/bin/activate
            while [ -z $ING_IP ]; do sleep 10; ING_IP=$(kubectl get ing -o=jsonpath='{.items[0].status.loadBalancer.ingress..ip}'); done
            export ING_DOMAIN=`kubectl get ing -o=jsonpath='{.items..spec.tls..hosts}' | sed 's/[][]//g'`
            echo "${ING_IP} ${ING_DOMAIN}" | sudo tee -a /etc/hosts
            cd ~/inferno-platform/tests
            pip install -q -r requirements.txt
            . run_test.sh
      - run:
          name: Delete cluster or wait 30 minutes
          command: |
            cd ~/inferno-platform
            export IF_DEBUG=`git log -1 --pretty=%B | grep "[[please debug me]]"`
            export PR_NR=`basename ${CIRCLE_PULL_REQUEST}`
            export SHORT_SHA1=`echo ${CIRCLE_SHA1} | cut -c 1-6`
            if [-n "$IF_DEBUG" ]; then
               sleep 30m
            fi
            echo y | gcloud container clusters delete inferno-${CIRCLE_BRANCH}-${SHORT_SHA1} --zone us-west1-a
      - run:
          name: Set images tags to latest on master
          command: |
            export BRANCH=$(git symbolic-ref --short HEAD)
            if [ "$BRANCH" == "master" ]; then
               MGMT_TAG=$(find management/ -type f -exec sha256sum {} \; | cut -d " " -f1 | sort | xargs echo | sha256sum | cut -d " " -f1)
               CTRL_TAG=$(find server-controller/ -type f -exec sha256sum {} \; | cut -d " " -f1 | sort | xargs echo | sha256sum | cut -d " " -f1)
               gcloud container images add-tag gcr.io/constant-cubist-173123/management-api:$MGMT_TAG gcr.io/constant-cubist-173123/management-api:latest
               gcloud container images add-tag gcr.io/constant-cubist-173123/server-controller-prod:$CTRL_TAG gcr.io/constant-cubist-173123/server-controller-prod:latest
            fi
workflows:
  version: 2
  deploy-test:
    jobs:
      - build
