{{- if .Values.openstack -}}
{{- $endpoint := .Values.global.minioEndpoint -}}
{{- $endpointUrl := .Values.global.minioEndpointUrl -}}
{{- else -}}
{{- $endpoint := printf "%s-%s" .Release.Name "minio.default.svc.cluster.local:9000" -}}
{{- $endpointUrl := printf "%s%s-%s" "http://" .Release.Name "minio.default.svc.cluster.local:9000" -}}
apiVersion: v1
kind: Secret
metadata:
  name: minio-access-info
type: Opaque
data:
  "minio.access_key_id": {{ .Values.global.accessKey | b64enc }}
  "minio.access_secret_key": {{ .Values.global.secretKey | b64enc }}
  "minio.endpoint": {{ $endpoint | b64enc }}
  "minio.endpoint_url": {{ $endpointUrl | b64enc }}
  "minio.minio_region": {{ .Values.global.minioRegion | b64enc }}
  "minio.signature_version": {{ .Values.global.minioSignatureVersion | b64enc }}
{{- end -}}
