apiVersion: v1
kind: Secret
metadata:
  name: dex
  namespace: {{ .Values.namespace }}
data:
  staticClient.id: {{ .Values.dex.id | b64enc }}
  staticClient.redirectURIs: {{ .Values.dex.redirectURIs | b64enc }}
  staticClient.secret: {{ .Values.dex.secret | b64enc }}
