apiVersion: v1
kind: Secret
metadata:
  name: custom-ca-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "dex_ca.crt": |-
{{ .Files.Get "certs/ca-dex.crt" | b64enc | indent 4 }}
