{{- if .Values.minio.secretCreate -}}
apiVersion: v1
kind: Secret
metadata:
  name: minio-access-info
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  "minio.access_key_id": {{ .Values.minio.accessKey | b64enc }}
  "minio.access_secret_key": {{ .Values.minio.secretKey | b64enc }}
  "minio.endpoint": {{ .Values.minio.endpoint | b64enc }}
  "minio.endpoint_url": {{ .Values.minio.endpointUrl | b64enc }}
  "minio.minio_region": {{ .Values.minio.minioRegion | b64enc }}
  "minio.signature_version": {{ .Values.minio.minioSignatureVersion | b64enc }}
{{- end -}}
