apiVersion: v1
kind: Secret
metadata:
  name: tls-ing-management-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  "tls.crt": |-
{{ .Files.Get "certs/ing-mgt-api.crt" | b64enc | indent 4 }}
  "tls.key": |-
{{ .Files.Get "certs/ing-mgt-api.key" | b64enc | indent 4 }}
