apiVersion: v1
kind: Secret
metadata:
  name: ca-cert-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "ca.crt": |-
{{ .Files.Get "certs/ca-cert-tf.crt" | b64enc | indent 4 }}
