apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: management-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: management-api
    spec:
      serviceAccountName: api-client
{{ if .Values.openstack }}
      imagePullSecrets:
        - name: gcr-json-key
{{ end }}
      containers:
      - name: management-api
        image: {{ .Values.image }}:{{ .Values.tag }}
        ports:
        - containerPort: 5000
        env:
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: PORT
          value: "5000"
        - name: MINIO_ENDPOINT_ADDR
          valueFrom:
            secretKeyRef:
              name: minio-access-info
              key: minio.endpoint_url
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-access-info
              key: minio.access_key_id
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-access-info
              key: minio.access_secret_key
        - name: PLATFORM_DOMAIN
          value: "{{ .Values.global.platformDomain }}"
        - name: STATIC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dex
              key: staticClient.id
        - name: STATIC_CLIENT_REDIRECT_URIS
          valueFrom:
            secretKeyRef:
              name: dex
              key: staticClient.redirectURIs
        - name: STATIC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dex
              key: staticClient.secret
        command:
        - /bin/sh
        - -c
        args:
        - /management/run.sh
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: management-api
  name: management-api
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: management-api
  type: LoadBalancer

