apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: management-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: management-api
    spec:
      serviceAccountName: api-client
{{ if .Values.openstack }}
      imagePullSecrets:
        - name: gcr-json-key
{{ end }}
      containers:
      - name: management-api
        image: {{ .Values.image }}:{{ .Values.tag }}
        ports:
        - containerPort: 443
        env:
        - name: MINIO_ENDPOINT_ADDR
          valueFrom:
            secretKeyRef:
              name: minio-access-info
              key: minio.endpoint_url
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-access-info
              key: minio.access_key_id
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-access-info
              key: minio.access_secret_key
        - name: PLATFORM_DOMAIN
          value: "{{ .Values.global.platformDomain }}"
        - name: STATIC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dex
              key: staticClient.id
        - name: STATIC_CLIENT_REDIRECT_URIS
          valueFrom:
            secretKeyRef:
              name: dex
              key: staticClient.redirectURIs
        - name: STATIC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dex
              key: staticClient.secret
        volumeMounts:
        - mountPath: /certs/
          name: tls-ing-management-secret
      volumes:
      - secret:
            defaultMode: 420
            secretName: tls-ing-management-secret
        name: tls-ing-management-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: management-api
  name: management-api
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: management-api
  type: ClusterIP

