apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}-app
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
            - name: S3_ENDPOINT
              value: {{ .Release.Name }}-minio.default.svc.cluster.local:9000
            - name: AWS_ENDPOINT_URL
              value: http://{{ .Release.Name }}-minio.default.svc.cluster.local
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-access-info
                  key: minio.access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-info
                  key: minio.access_secret_key
            - name: AWS_REGION
              value: us-east-1
            - name: BUCKET_NAME
              value: bucket-model
            - name: S3_USE_HTTPS
              value: "0"
            - name: S3_VERIFY_SSL
              value: "0"
          command:
          - /bin/sh
          - -c
          args:
          - ./tensorflow_model_server --port=9000 --model_name=resnet --model_base_path="s3://bucket-model/resnet"
          ports:
          - containerPort: 9000
