apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "alpine:3.3"
        command: ["/bin/sh"]
        args: ["-c", "apk add --update python python-dev py-pip && apk update && apk add ca-certificates wget && update-ca-certificates && pip install awscli && aws configure set default.region us-east-1 && aws configure set aws_access_key_id {{ .Values.global.accessKey }} && aws configure set aws_secret_access_key {{ .Values.global.secretKey }} && wget https://storage.googleapis.com/inference-eu/resnet-saved-model/0/saved_model.pb && mkdir -p resnet/resnet/0/variables && mv saved_model.pb resnet/resnet/0 && aws --endpoint-url http://{{ .Release.Name }}-minio.default.svc.cluster.local:9000 s3 mb s3://bucket-model && aws --endpoint-url http://{{ .Release.Name }}-minio.default.svc.cluster.local:9000 s3 sync ./resnet s3://bucket-model/"]
